### ISSUE TITLE
Allow import of D&D Beyond JSON

### ISSUE THREAD

**Issue by Majawat** [HarmlessKey/HarmlessKey#15]
You can get JSON files of player characters from D&D Beyond, it'd be awesome to import that data into Harmless Key so I don't have to manually enter (not that there's much). I can provide sample data if needed.

**Comment by HarmlessHarm** [comment]
This is something we really want to look into!

**Comment by Lakeyzer** [comment]
@Majawat It took 4 years (almost to the day), but it's finally here! In our latest release (2.9.0) it's possible to sync your players with characters from external resources using the [D&D Character Sync](https://chrome.google.com/webstore/detail/dd-character-sync/jgcbbmbchbkdjbgiiheminkkkecjohpg) Chrome Extension.
