### ISSUE TITLE
Unable to reset encounter

### ISSUE THREAD

**Issue by jarrodwhitley** [HarmlessKey/HarmlessKey#165]
![Screen Shot 2023-06-14 at 9 01 15 AM](https://github.com/HarmlessKey/HarmlessKey/assets/11711674/ccc4c7df-2745-4de3-b49a-4cbb95a8a864)
![Screen Shot 2023-06-14 at 8 59 56 AM](https://github.com/HarmlessKey/HarmlessKey/assets/11711674/f2cb444c-e5e6-47ca-97a9-8db9c43d263d)

Steps to reproduce:

- Enter encounter
- Stop broadcasting
- Finish encounter (with enemies still alive)
- Click reset button

After refreshing the page I was able to reset the encounter.

**Comment by Lakeyzer** [comment]
This is fixed in #170
Thanks for the report!
