### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'roll')

### ISSUE THREAD

**Issue by jarrodwhitley** [HarmlessKey/HarmlessKey#166]
I'm seeing his error in the console when I attempt to do an attack roll with an enemy NPC. May be related to https://github.com/HarmlessKey/HarmlessKey/issues/165

After I stopped the broadcast I was able to roll again.

![Screen Shot 2023-06-14 at 9 08 21 AM](https://github.com/HarmlessKey/HarmlessKey/assets/11711674/a9333441-b20d-468f-93f8-675e9e81f2d4)

**Comment by Lakeyzer** [comment]
We're looking into this right now and found the source of the problem, it will be fixed soon. Thanks for your report!

**Comment by HarmlessHarm** [comment]
Fixed in #169
